# Generated by Django 4.2.5 on 2023-11-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsapp_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsapp',
            name='news_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='newsFiles/'),
        ),
    ]
