# Generated by Django 4.2.5 on 2023-09-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactenquiry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactenquiry',
            name='websiteLink',
        ),
    ]
